### ISSUE TITLE
Specify input (keyboard/mouse/touch/pointer)

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver-bidi#121]
BiDi will need an equivalent to [WebDriver's Action API](https://w3c.github.io/webdriver/#actions) in order to click buttons, write text into form controls, etc.

Aside/prediction: This is probably more involved than most of WebDriver BiDi so far, since at least CDP isn't very similar to the Actions API. My understanding is that the implementation in ChromeDriver is not a trivial mapping to CDP, because the input needs to be injected at the right layer in the stack to be as close as possible to real input, which is not necessarily the process that CDP is connected to.

**Comment by jgraham** [comment]
FWIW my initial feeling here is that this is a case where we should adopt the WebDriver approach rather than trying to copy CDP and layer the WebDriver semantics on top. The main concern would be whether that's a probelm for clients like Puppeteer which are using CDP. I hope that simple/common things will have a mostly trivial mapping but we'll make it easier to handle complex multi-input scenarios.

**Comment by foolip** [comment]
That is my inclination too, but whichever we way go I expect this won't be trivial.

Puppeteer has things like [`page.touchscreen`](https://github.com/puppeteer/puppeteer/blob/v10.1.0/docs/api.md#pagetouchscreen) and [`keyboard.type`](https://github.com/puppeteer/puppeteer/blob/v10.1.0/docs/api.md#keyboardtypetext-options) which probably can map to WebDriver Actions, but we'd be lucky if all the details about what coordinates mean and whether any scrolling/focusing happens automatically aligns perfectly across the board here.

**Comment by jimevans** [comment]
I’ve recently begun prototyping a greenfield bidi-only client library, and this is likely to become a need in the medium-term. I realize this issue is our proverbial stake in the ground to indicate that user inputs are not simply a special case of executing script. Having said that, the WebDriver classic semantics do seem to be well thought-out here, and pretty well understood. Porting those semantics, even almost wholesale, seems a reasonable approach.

**Comment by jgraham** [comment]
https://github.com/w3c/webdriver-bidi/pull/175 is the proposed implementation here, but note that's blocked on https://github.com/w3c/webdriver/pull/1653

**Comment by thiagowfx** [comment]
https://github.com/w3c/webdriver-bidi/pull/175 is now merged. Can this be closed?

**Comment by whimboo** [comment]
Yes, it seems to be all done in the meantime.
