### ISSUE TITLE
"log.entryAdded" event misses reference to browsing context or realm in its payload

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#146]
Events for `log.entryAdded` currently only contain the actual data related to the log entry, but clearly miss their origin. Like say executing a `console.log('foo')` script across different browsing contexts doesn't allow to differentiate the individual log events when having subscribed to the event globally. That makes it impossible for the client to filter out and assign these entries. 

As such I would propose to get the browsing context id, or a realm id added to the payload of the log event.

**Comment by whimboo** [comment]
@CC @jgraham

**Comment by whimboo** [comment]
See also https://github.com/w3c/webdriver-bidi/pull/73#discussion_r564461083 why a browsing context id hasn't been added (yet). I'll let @jgraham decide here.

**Comment by bwalderman** [comment]
Looks like the original reason stated in [the comment from #73](https://github.com/w3c/webdriver-bidi/pull/73#discussion_r564461083) was because it wasn't yet clear what a "context" property should look like. It could be either a browsing context, or a realm in cases where there is no browsing context (e.g. a ServiceWorker).

Since that comment was posted, we've defined the [script.Target](https://w3c.github.io/webdriver-bidi/#type-script-Target) type which could fit this role. The `log.entryAdded` event could provide an origin" property of type Target that has a `context` when it comes from a context, or a `realm` otherwise.

**Comment by whimboo** [comment]
Note that PR #167 will add an `origin` property to the `RealmInfo` type which then could be used here.

And just noticed that for `JavascriptLogEntry` entries we do not have a `realm` set because it's only available for `ConsoleLogEntry`. Should we maybe move the `realm` property to the `BaseLogEntry`?

**Comment by whimboo** [comment]
There is now the question if we could re-use the `Target` type from the script module for the purpose of telling the client which realm or browsing context a given log message is originating from. Then there is also the optional `sandbox` parameter for this type, which actually might be helpful as well if a script running inside a sandbox logs these events.

If we want to allow the additional `sandbox` information within the event's payload, should we re-use this type, and add a new `target` property to the `Log.BaseLogEntry` type?

**Comment by whimboo** [comment]
This was fixed with PR #209.
