### ISSUE TITLE
Decide on a value serialization format

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#16]
Remote automation frequently requires serializing js objects and handles to DOM objects over the network. Different serialization formats are possible here with different tradeoffs. We should ensure we make an intentional decision for the format we use for the BiDi protocol; in particular it need not be the same as that for the HTTP protocol, although we *do* have a requirement to be able to share object handles i.e. it must be possible for a client (local end) to transform a WebElement from the HTTP protocol into a form where it can be transmitted over BiDi and will end up refering to the same element.

### WebDriver / HTTP

JS values are serialized as JSON. Handles to elements and windows are serialized using a special object format that's included inline in the JSON. Other values that aren't in JSON (e.g. BigInt, Infinity, etc.) aren't supported at all.

### CDP

Any remote object can be represented via a [RemoteObject](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-RemoteObject) object. This includes a mechaism for returning json serialized values where that is possible, and for representing js primitives that aren't serializable as json. However there isn't a mechanism for representing e.g. an array of elements, which means that something like findElements may require repeated trips over the API.

### Firefox RDP

https://docs.firefox-dev.tools/backend/protocol.html#grips

**Comment by jgraham** [comment]
#57 will address this

**Comment by foolip** [comment]
In order to understand more of how this works in CDP, I tried some things using the approach in https://github.com/w3c/webdriver-bidi/issues/14#issuecomment-633568306. Note that `DEBUG=puppeteer:protocol:*` is needed. CDP's `Runtime.evaluate` has a `returnByValue` parameter which controls the behavior. (I used Puppeteer's `page.evaluate` and `page.evaluateHandle` to test the difference.)

<table>
<tr><th>JS expr</th><th><code>returnByValue</code> true</th><th><code>returnByValue</code> false</th></tr>
<tr><td><code>[1, 2, 3]</code></td><td><code>{"type":"object","value":[1,2,3]}</code></td><td><code>{"type":"object","subtype":"array","className":"Array","description":"Array(3)","objectId":"{\"injectedScriptId\":3,\"id\":1}"}</code></td</tr>
<tr><td><code>{a:1, b:2}</code></td><td><code>{"type":"object","value":{"a":1,"b":2}}</code></td><td><code>{"type":"object","className":"Object","description":"Object","objectId":"{\"injectedScriptId\":3,\"id\":1}"}</code></td</tr>
<tr><td><code>x = {}; x.self = x; x</code></td><td><b>error</b>: <code>{"code":-32000,"message":"Object reference chain is too long"}</code></td><td><code>{"type":"object","className":"Object","description":"Object","objectId":"{\"injectedScriptId\":3,\"id\":1}"}</code></td</tr>
<tr><td><code>null</code></td><td><code>{"type":"object","subtype":"null","value":null}</code></td><td><code>{"type":"object","subtype":"null","value":null}</code></td</tr>
<tr><td><code>undefined</code></td><td><code>{"type":"undefined"}</code></td><td><code>{"result":{"type":"undefined"}</code></td</tr>
<tr><td><code>document.createElement("div")</code></td><td><code>{"type":"object","value":{}}</code></td><td><code>{"type":"object","subtype":"node","className":"HTMLDivElement","description":"div","objectId":"{\"injectedScriptId\":3,\"id\":1}"}</code></td</tr>
</table>

So it looks like CDP has two serialization modes, one where it tries to "deep serialize" and throws an exception given cycles, and another where it uses object IDs where necessary, but primitive values are still serialized like in the other mode. Notably, elements don't seem to be special in either mode.

**Comment by jgraham** [comment]
Right, the proposal in #57 is somewhat intentionally looking at where CDP is going, and trying to remove a few layers of legacy from that. In particular the experimental `preview` field looks like it does deep object serialization of the kind that we need to support to do things like pass an array of elements back in a single call.

Handling node subclasses directly basically means we wouldn't have to do `describeNode` as a seperate call. I think it makes sense to users that we'd just return the useful information by default rather than requiring multiple calls to get at it.

**Comment by jgraham** [comment]
The initial PR here merged, so I'm going to  close this.
