### ISSUE TITLE
Specify closing a browsing context

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#170]
Beside issue #116 (PR #133) we would also need a command to close a browsing context.

**Comment by whimboo** [comment]
We should be clear about what should happen when the last browsing context gets closed. I assume it will be similar to the WebDriver HTTP specification, so that the browser quits and the session will be closed?

CC @jgraham

**Comment by jgraham** [comment]
This also needs to fail if the context isn't a top level browsing context.

**Comment by juliandescottes** [comment]
PR #172 was open to fix this, but there are two items we should discuss:
1. What should happen when we close the last tab/window:
    - explicitly close the browser and end the session (same as webdriver classic?)
    - leave the decision to the implementation
    - do nothing but expose another command to close the browser (Browser.close ?)
2. What should be the return value of browsingContext.close
    - Nothing
    - List or count of remaining top level browsing contexts
    - List or count of remaining windows

**Comment by juliandescottes** [comment]
Another thing to consider: Puppeteer currently supports a `runBeforeUnload` parameter for Page.close: https://pptr.dev/#?product=Puppeteer&version=v1.20.0&show=api-pagecloseoptions

Internally it will switch between CDP's Page.close and Target.closeTarget depending on the value of this parameter, but maybe this is something we should handle directly in the BrowsingContext.close command for BiDi?

**Comment by juliandescottes** [comment]
Quick note about CDP: testing CDP's Page.close, at least on Mac calling Page.close on the last tab doesn't close the Chrome application itself, although the behavior is probably different on Linux/Windows.

**Comment by juliandescottes** [comment]
No strong opinions for the return value (but some options for closing the last tab/window might make use of the return value to communicate the behavior to the consumer).
Regarding onBeforeUnload, no strong opinions either, could be done differently if needed (re-reading the transcript, maybe it was not clear that the proposal was to have a flag to skip before unload promps, not to run code at beforeunload).

Most of the discussion revolved around the behavior when closing the last tab/window.

One should read the conversation above for more context, but a short summary is that we want to enforce consistent behavior as much as possible with WebDriver BiDi, and closing the browser is the only consistent behavior that could be enforced by WebDriver. This is what WebDriver HTTP does. It was also mentioned that closing the browser encourages proper test isolation. But tools such as Puppeteer currently close the last tab/window in headless mode and expect the browser to stay alive, so that they can open a new tab/window for the next task. So doing exactly the same as WebDriver HTTP would be a regression here, or would for the tools to keep a tab open in the background to keep the browser alive.

The suggested alternative was that closing the browser could be left unspecified, and be an implementation detail. Instead the spec could just expect that the session should be closed when the last tab/window is closed. Meaning that a tool such as puppeteer would not have to restart the browser between tests but would still have to create a new session for each test.

@mathiasbynens @jschfflr hi! Do you have any feedback about the proposal above? If closing the last tab/window would close the session (but not necessarily the browser), how inconvenient would that be for you? Do you foresee performance issues with this?

**Comment by juliandescottes** [comment]
I want to note that we also discussed an option based on capabilities, which after thinking about it outside of the meeting feels compelling to me.

By default, closing the last tab/window would always close the browser.
The user can request a capability such as `keepBrowserAfterAllWindowsClosed`.
If the target browser does not support this behavior, the session will not be created.
If it does, the session should be created successfully and the browser should not close when the last tab/window is closed.

The downside of this is that tests written for a browser with `keepBrowserAfterAllWindowsClosed` will not be portable to a browser which doesn't support it. But at least the default behavior would be consistent, so that you have to opt-in to expose yourself to inconsistencies.
