### ISSUE TITLE
Specify focusing another (top-level) browsing context

### ISSUE THREAD

**Issue by whimboo** [w3c/webdriver-bidi#171]
It should be possible to switch between different top-level browsing contexts. Not sure if setting the focus for individual child browsing contexts would be needed.

**Comment by thiagowfx** [comment]
This would be great to enhance `browsingContext.captureScreenshot`.

Currently, the chromium mapper implementation needs to focus the context in order to take the screenshot (otherwise it blocks / hangs). We're currently doing so with our custom implementation (via CDP). If there were an official BiDi way to do it, then we could just use it instead.

**Comment by OrKoN** [comment]
Completed in https://github.com/w3c/webdriver-bidi/pull/453
