### ISSUE TITLE
Remove `url` and `children` fields for `browsingContext.contextCreated`

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#220]
According to the specification, the `browsingContext.contextCreated` will always be raised with `url: 'about:blank'` and `children: []`. Having those fields in the event seems confusing. Let's cut the info to the   following:
```
  context: BrowsingContext,
  ?parent: BrowsingContext / null,
```

**Comment by foolip** [comment]
The reason that the URL should always be about:blank is because https://w3c.github.io/webdriver-bidi/#event-browsingContext-contextCreated is invoked after step 19 in https://html.spec.whatwg.org/multipage/browsers.html#creating-a-new-browsing-context before there's been any navigation.

I'm not sure if it's possible for a tree of iframes to be created synchronously, there probably is, but even then I don't know if the children need to be listed, since events for each of the children should follow soon after.

**Comment by foolip** [comment]
I tried some things in the "sync creation" depeartment. This shows that at least nested `<iframe srcdoc>` aren't created syncronously:
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=10359

The spec treats `<iframe>` and `<frame>` differently at one point, so I thought maybe nested `<frame>` would be sync:

```html
<!DOCTYPE html>
<frameset>
<frame src="data:text/html,<frameset><frame src='data:text/html,hello frame'></frameset>"></frame>
</frameset>
```

But it seems like parsing of `<script>` is special in `<frameset>` so I can't add the logs to check.

Anyway, if it's possible I think we should still make it look the same in the protocol, so no `children`. Does anyone remember why we added that field?

**Comment by sadym-chromium** [comment]
> Anyway, if it's possible I think we should still make it look the same in the protocol, so no `children`. Does anyone remember why we added that field?

I guess the answer is "Those fields were added for `browsingContext.getTree` and wasn't removed from the events.".

**Comment by foolip** [comment]
Aha, that would explain it. Just context and parent as suggested makes more sense to me.

**Comment by whimboo** [comment]
When I implemented the event in Firefox I had to fight with some race conditions regarding the currently loaded URL. And in some cases (around frame creation) intermittent failures are still present. As such I'm fine with getting the `url` property removed. 

Regarding the `children` part... Given by the spec the code that creates the `browsingContext.contextCreated` event calls [get the browsing context info](https://w3c.github.io/webdriver-bidi/#get-the-browsing-context-info) with a `maxDepth` of `0`. This means that step 6 of this method will not modify `child infos` which by default is`null`. I assume that step 7 should get a `or unset otherwise` in case of `maxDepth` is `0`?

CC'ing @jgraham as well for his feedback.

**Comment by jgraham** [comment]
Note that we emit these events for existing contexts if you subscribe after the context was created. So URL can be populated in that case, but as whimboo mentions the `children` property will always be null because we just emit one event per context recursively rather than one for the whole tree. Possibly that should change?

**Comment by sadym-chromium** [comment]
> jgraham: We chose the current design to allow the client to just listen to the contextCreated events and be up to date with the current state of the browser in a race-free way. Also similar to CDP. Could just emit one event per top-level context with children, which would be less traffic but also different to the events you would have got if you'd already subscirbed when the contexts were first created.

Just to summarise: 
`browsingContext.contextCreated` is used not only to notify about new contexts, but to notify users about pre-existing events. Current spec version sets url always to `about:blank`. I created a PR to align WPT with such behaviour: https://github.com/web-platform-tests/wpt/pull/34641

**Comment by sadym-chromium** [comment]
yes, let's we can keep `children`
