### ISSUE TITLE
CDDL for EmptyParams

### ISSUE THREAD

**Issue by zcorpan** [w3c/webdriver-bidi#241]
I'm a bit confused about this CDDL fragment:

```
EmptyParams = { *text }
```

Is it intended to be

```
EmptyParams = { *text => any }
```
?

**Comment by whimboo** [comment]
Our [CDDL test in CI](https://github.com/w3c/webdriver-bidi/runs/7028255505?check_suite_focus=true) doesn't fail on that. @jgraham could you answer please?

**Comment by jgraham** [comment]
Yes, it's supposed to be the latter.

I like the idea of defining `Extensible = (*text => any)` and then defining `EmptyParams = {Extensible}`

**Comment by dprevost-LMI** [comment]
Hey, this one has been a while, but before entering a new issue, which I could, why is EmptyParams not in fact empty, so `EmptyParams = {}` since by using `Extensible` it is not empty.
Otherwise, could that actually be named AnyParams and not EmptyParams?

On my side, I'm trying to generate some Typescript code from CDDL in WebdriverIO for that, and the object name clashes with it definition 🤔

**Comment by nvborisenko** [comment]
😳 same concerns: https://github.com/SeleniumHQ/selenium/issues/15562
