### ISSUE TITLE
Serialization format: add suffix `n` to BigInt's value

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#255]
Discussible topic, no strong opinion here:
Should we consider adding suffix `n` at the end of BigInt's value, so that it can be evaluated directly?

**Comment by sadym-chromium** [comment]
@jgraham wrote in #254:
> The `"1"` →`"1n"` `BigInt` change arguably is adopting a peculiarity of ECMAScript into the protocol (a client in another language is going to have to strip out the `n` in order to parse the numeric value; even an ECMAScript implementation can just call `BigInt("1")`, but not `BigInt("1n")`). So I think I'd prefer not to take that one. But I don't feel very strongly either way.

**Comment by jgraham** [comment]
There are two tradeoffs here:
* In non-ECMAScript languages it may be possible to evaluate the unsuffixed version directly (e.g. this would work in Python).
* In ECMAScript, passing the unsuffixed version to `BigInt` works, but the suffixed version does not (i.e. `BigInt("1") works but `BigInt("1n")` doesn't).

Given that we're explicitly type-tagging the values, the second point in particular suggests to me that we shouldn't change the serialization here, since using `BigInt` is generally preferable to using `eval`.

**Comment by sadym-chromium** [comment]
Agree. Closing the issue.
