### ISSUE TITLE
Simulating user gesture during script evaluation (`script.evaluate`, `script.callFunction`)

### ISSUE THREAD

**Issue by OrKoN** [w3c/webdriver-bidi#359]
Puppeteer provides the ability to evaluate JavaScript while emulating the user action. In the following test, the expected result is true although there was no explicit user action to trigger the execution of the script:

```
   it('should simulate a user gesture', async () => {
      const {page} = getTestState();

      const result = await page.evaluate(() => {
        document.body.appendChild(document.createTextNode('test'));
        document.execCommand('selectAll');
        return document.execCommand('copy');
      });
      expect(result).toBe(true);
    });
```

it looks like WebDriver BiDi does not offer this capability yet but it probably should be added. In CDP, the userGesture flag is responsible for this feature: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

**Comment by jgraham** [comment]
Hmm, so I don't know off the top of my head how well this approach works cross browser. It might be fine, but we'd need to discuss.

FWIW in web-platform-tests we work around this using [`testdriver.bless`](https://github.com/web-platform-tests/wpt/blob/3701ae5cb63cde1da20db6592eff7e80b495cabd/resources/testdriver.js#L103-L124) which ties the script to an actual user action. It's a bit ugly because it requires DOM manipulation to insert the `<button>` but it at least seems to work well enough for wpt use cases.

**Comment by foolip** [comment]
Perhaps we could have a way for BiDi to set the [stick activation](https://html.spec.whatwg.org/multipage/interaction.html#sticky-activation) and [transient activation](https://html.spec.whatwg.org/multipage/interaction.html#transient-activation) state, either as its own API, or just in the scope of a single script evaluation?

**Comment by OrKoN** [comment]
@jgraham I have opened a PR for this here https://github.com/w3c/webdriver-bidi/pull/496 WDYT?
