### ISSUE TITLE
Add `browsingContext` parameter to `script.addPreloadScript`

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#373]
Currently, there is no way for the ["preload script"](https://w3c.github.io/webdriver-bidi/#preload-script) to be run only in specific BrowsingContext, and there is not way for the script to determine in which browsing context it is running, which makes some scenarios quite hard to implement. E.g. scenario "setup mutation observer on a page I'm about to navigate".

I suggest adding either `context: browsingContext.BrowsingContext` or `?contexts: [*browsingContext.BrowsingContext]` parameter to the [`script.addPreloadScript`](https://w3c.github.io/webdriver-bidi/#command-script-addPreloadScript) command.

**Comment by juliandescottes** [comment]
I think we have the same constraint here as for events, meaning we can't set a preload script for non top-level contexts. The context id for a non top level browsing context should not survive navigation, so you can't schedule a preload script specifically for let's say an iframe.

With this in mind, if we pass a context (top-level) to `addPreloadScript`, should it also load the script in all the child contexts?

**Comment by sadym-chromium** [comment]
Yes, all non-top-level browsing contexts inherits it from the top-level parent.

**Comment by juliandescottes** [comment]
To clarify: the context id will be preserved if we navigate the frame only, but not if we navigate the top level document. I was mixing up the two scenarios. 

Nevertheless it seems practical to inherit preload scripts in non-top-level contexts, because top level navigations are the most common scenario.

**Comment by sadym-chromium** [comment]
> To clarify: the context id will be preserved if we navigate the frame only, but not if we navigate the top level document. I was mixing up the two scenarios.
> 
> Nevertheless it seems practical to inherit preload scripts in non-top-level contexts, because top level navigations are the most common scenario.

My understanding is: Navigating top level document keeps the `browsingContext` (tab), but changes `navigable` (specific document).

**Comment by jgraham** [comment]
No, the `navigable` is the top-level tab or iframe, the `Document` is the document and the `browsingContext` isn't quite either (it's close to navigable, but changes for some cross-origin navigations).

I think inheriting to descendents by default makes sense. I'm not sure if only allowing the context to be a top-level context makes sense; if you know you're going to navigate an iframe having to add the script to the top-level frame seems more complex (note that I don't think we have the same problem as we have for event subscriptions because we don't have a generic unsubscribe, but a handle to remove a specific preload script, which removes it from all the contexts in which it was added).

**Comment by thiagowfx** [comment]
cc @foolip so you subscribe to updates here

**Comment by sadym-chromium** [comment]
So it should be top-level `navigable` then (which is still called BrowsingContext).

**Comment by thiagowfx** [comment]
Previous PR attempt: https://github.com/w3c/webdriver-bidi/pull/411.

**Comment by OrKoN** [comment]
@Lightning00Blade wanted to work on this (cc @thiagowfx)
