### ISSUE TITLE
Support for web hardware communication apis

### ISSUE THREAD

**Issue by rajsite** [w3c/webdriver-bidi#408]
Would be helpful for the webdriver protocol to allow emulating the API surface area for hardware communication apis like:

- Web Bluetooth
- Web Serial
- WebUSB

I.e. emulate the discovery of devices, notify user selection, two-way communication, disconnection and error sates, etc.

**Comment by jgraham** [comment]
That isn't going to happen in this working group for two reasons:
* Specific non-core APIs that want to add automation support are better off doing that work in the context of the groups designing the APIs since they have specific domain knowledge that's important to getting a good design. 
* None of the technologies you mentioned are on a standards track, and some vendors believe their current design comes with unacceptable tradeoffs that mean they aren't suitable for the web platform.

Therefore I'm going to close this issue; as mentioned you're better off directly talking to the people who are implementing these APIs.
