### ISSUE TITLE
Specify navigating a browsing context

### ISSUE THREAD

**Issue by foolip** [w3c/webdriver-bidi#43]
One of the first things any automation script will do is to get a browsing context (https://github.com/w3c/webdriver-bidi/issues/42) and navigate it. Navigating a browsing context is therefore something we'll want to work on fairly early, although it might not be the very first command.

At a high (enough) level it should be very similar to https://w3c.github.io/webdriver/#navigate-to, but there are plenty of considerations:
- Should the command return as soon as the navigation is started ([navigate](https://html.spec.whatwg.org/#navigate) sync steps done) or [wait for navigation to complete](https://w3c.github.io/webdriver/#dfn-waiting-for-the-navigation-to-complete) like WebDriver classic does?
- If there is waiting, is the [page loading strategy](https://w3c.github.io/webdriver/#dfn-page-loading-strategy) a parameter?
- Which events have to fire while navigating a browsing context?

**Comment by jgraham** [comment]
On waiting vs no waiting, what's does the precedent look like here in devtools/clients. I assume that the model is "no waiting, you have to listen for the events you want to use to determine the page is loaded enough", but maybe that's too low-level (it's certainly going to be at least one mode, since it basically corresponds to the pageLoadingStrategy of none).

**Comment by bwalderman** [comment]
In CDP, when you send the `Page.navigate`, the command returns once the navigation has committed and the return value is a frameId

**Comment by bwalderman** [comment]
In CDP when you send a `Page.navigate` command, it responds as soon as the navigation has committed and the response includes a frameId you can use to keep track of events coming from that frame. We could do something similar by default (basically the "none" strategy) but also allow the client to pass in a page loading strategy of "eager" or "normal" if they want classic semantics.

**Comment by whimboo** [comment]
As reference in Puppeteer the navigation immediately returns by default when the HTTP response has been received. If it should wait longer the [waitUntil](https://github.com/puppeteer/puppeteer/blob/main/src/common/FrameManager.ts#L621) argument can be used to extend the wait for one or more lifecycle events like `DOMContentLoaded`, `load`, or even `networkidle0` or `networkidle2` (no more HTTP traffic).

**Comment by foolip** [comment]
The above minutes are from https://www.w3.org/2020/10/27-webdriver-minutes.html#t02. I'd like to ask for clarification on the proposed model to make sure I understand it correctly.

My understanding is that we'd have a "context.navigate" command (assuming https://github.com/w3c/webdriver-bidi/pull/62) with an optional parameter taking [WebDriver Classic](https://w3c.github.io/webdriver/#navigation)'s values "none", "eager" and "normal". The command would be potentially long running, and the command response (containing the command ID) would only be sent once the page was loaded to the requested point.

Separately, there would be events corresponding to a change in [current document readiness](https://html.spec.whatwg.org/#current-document-readiness) which one could enable to get events and precisely before (or after?) the "context.navigate" command response is sent.

Some of the details are from my assumptions, but does sound right?

If that is right, then I wonder if the protocol itself needs to provide two ways to achieve the same thing, as opposed to leaving ergonomic shorthands to client libraries? Or is there something that would be harder than it first appears if one had to rely on just events?

**Comment by jgraham** [comment]
I think that's correct.

The concern about leaving this to libraries is that it can be very hard to get right. The typical edge case is that you request a load and before the command is fully processed you get an event from another pending load (which might even be e.g. an about:blank) and mistakenly assume that the load you scheduled is complete. So clients probably need to be careful to track the request id (CDP: loader id), but if they aren't it will mostly work just with occasional races (and maybe the opposite race is already possible where you get a load that you did initiate, but before you've registered the appropriate request id). Meanwhile the browser side needs to get this right anyway, so why not provide some slightly higher level primitives to make common cases easier whilst still providing the necessary primitives to do something more advanced.

Alternative framing: providing the commonly used options as explicit modes is favoured by the Priority of Contistuencies since it means library authors don't all have to reimplement the same non-trivial logic.

On another note, I wonder how we specify a request id. I bet that's not exposed in the standards.

**Comment by whimboo** [comment]
Given that the current navigation logic is not always enough to await a page to be loaded, I wonder if we should pick-up the [`networkIdle` and `networkAlmostIdle` like lifecycle events from CDP](https://github.com/puppeteer/puppeteer/blob/main/src/common/LifecycleWatcher.ts#L35-L39). Those (or only the idle one) could be mapped as new page load strategies, or arguments.

If we would consider using these we might have to take care of observing the activity for network channels as currently used for the request via network events.

**Comment by foolip** [comment]
@jgraham do you think we could ensuring that the logic is trivial, by first specifying the corresponding events, and defining page load strategy in terms of the hooks for those events? The convenience wrapper, whether in implementations to support a page load strategy parameter, or in client libraries for more advanced cases, should ideally be:
- subscribe to the appropriate events
- initiate the navigation, get some ID from the response
- wait for the appropriate event with that ID

If it's any more complicated than that, then I'd question if we've exposed the right events to allow for the more advanced cases.

**Comment by jgraham** [comment]
That's how I'd expect that things work out. It may turn out that the page load strategy stuff isn't a huge value add, but I also think it's not going to be difficult to specify or implement and in the TPAC discussion there seemed to be a strong consensus that creating the higher-level abstraction here is a real benefit.

@whimboo : Do we know what heuritics those events are using? It seems like the kind of thing that could be an interop concern if browsers do slightly different things (e.g. a test could depend on a resource being loaded in browser A that has not in fact completed loading in B).

**Comment by whimboo** [comment]
> @whimboo : Do we know what heuritics those events are using? It seems like the kind of thing that could be an interop concern if browsers do slightly different things (e.g. a test could depend on a resource being loaded in browser A that has not in fact completed loading in B).

@mathiasbynens maybe you could given some feedback here regarding the `networkIdle` and `networkAlmostIdle` events? See also my [last comment from above](https://github.com/w3c/webdriver-bidi/issues/43#issuecomment-721112984).

**Comment by jgraham** [comment]
From #62:

> CDP has a separate Page.frameNavigated event. Navigating a browsing context will indeed result in the tree of browsing contexts changing, but I agree it's not clear how best to represent that.

Maybe as a part of this work we need to decide if we want to have contextDestroyed events when contexts become inactive, even if they are alive in the bfcache. Or if we want another kind of event or just to have a navigation event and let clients figure out that contexts under the navigated context are inactive if not destroyed.

**Comment by jgraham** [comment]
I've been making some progress on this locally. It looks like we're going to need quite a lot of integration points in the HTML spec; I've filed https://github.com/whatwg/html/issues/6429 for that. The idea is that each async navigation (i.e. excluding fragment navigations or those that fail early) will get a navigation id, which I think is the analouge of the loader id in CDP.

API wise, I'm currently thinking:
* A `browsingContext.navigate` command that takes a browsing context id, an optional `waitUntil` parameter which determines whether to return as soon as the HTML navigate algorithm starts running async, or to (asynchronously) wait until either `DOMContentLoaded` or `load` for the relevent context for the navigation id that's created (for fragment navigations we always return straight away; there are also various error conditions here that need to be handled and stuff like navigation ending in a download rather than a document load). In all async cases this returns the navigation id of the navigation that was started.
 - One outstanding question here is whether this ought to take a timeout parameter or if we're OK with putting that logic on clients. 
* A `browsingContext.navigationStarted` event that provides the context id, navigation id, and url for any non-fragment navigation (either client-initiated or browser initiated).
* A `browsingContext.fragmentNavigated` event that provides the context id and url for any synchronous navigation e.g. a fragment navigation (could maybe rename this to match `Page.navigatedWithinDocument` from CDP and verify the semantics match for history API usage).

The remaining events are a bit uncertain. I think we need something close to `Page.downloadWillBegin` for navigations that end in a download. For observing the later stages of document-load type navigations, CDP has `Page.lifeCycleEvent` that also covers things like painting which are harder to specify cross-browser. AFAICT the special thing about this event is that it is part of the page domain but has to be explictly enabled. I assume the per-event subscription model in BiDi means we don't require this extra switch.

I assume that we're going to need at least:
* A `browsingContext.domContentLoaded` event with the context id, navigation id, and url.
* A `browsingContext.load` event with the context id, navigation id, and url.

I assume that the other lifecycle events are out of scope for this bug. The only concern is whether clients want to depend on `network[Almost]Idle` for waiting for a stable state after load, and how that's defined.

**Comment by whimboo** [comment]
>     * A `browsingContext.navigate` command that takes a browsing context id, an optional `waitUntil` parameter which determines whether to return as soon as the HTML navigate algorithm starts running async, or to (asynchronously) wait until either `DOMContentLoaded` or `load` for the relevent context for the navigation id that's created (for fragment navigations we 
always return straight away; there are also various error conditions here that need to be handled and stuff like navigation ending in a download rather than a document load). 

So what about the network idle specific values that CDP currently supports, and probably emits on its own after some time without network activity for the `loaderId`? It's more reliable to detect when a navigation has actually been done, and no more resources are loaded. I'm fairly sure this will be a request from a lot of users.

>     * One outstanding question here is whether this ought to take a timeout parameter or if we're OK with putting that logic on clients.

If the timeout is on the client side there must be a way to actually run a clean-up on the remote end. With the navigation various event handlers etc might have been set internally by the browser, which need to be removed again in case the page doesn't finish loading.

> I assume that we're going to need at least:
> 
>     * A `browsingContext.domContentLoaded` event with the context id, navigation id, and url.
> 
>     * A `browsingContext.load` event with the context id, navigation id, and url.

As reference here a list of page.* events that CDP actually emits:
```
    "frameStartedLoading",
    "frameNavigated",
    "domContentEventFired",
    "loadEventFired",
    "navigatedWithinDocument",
    "frameStoppedLoading",
```

Some of them are actually marked as experimental. And as mentioned by @jgraham there are also the lifecycle events.

**Comment by jgraham** [comment]
> So what about the network idle specific values that CDP currently supports, and probably emits on its own after some time without network activity for the `loaderId`? It's more reliable to detect when a navigation has actually been done, and no more resources are loaded. I'm fairly sure this will be a request from a lot of users.

I think it's a reasonable feature request, but it's at least non-trivial to specify so I'm inclined to leave it until later (once we have some integrations into fetch, for example).

> If the timeout is on the client side there must be a way to actually run a clean-up on the remote end. With the navigation various event handlers etc might have been set internally by the browser, which need to be removed again in case the page doesn't finish loading.

That problem doesn't seem related to timeouts as such; if the browser is stuck in a never-stops-loading state the fact that we've registered some event handlers isn't the biggest problem. If the navigation does complete eventually we'll go through the normal unregistering process once it does and emit a message that the client will proceed to ignore. But that doesn't seem like loads of potential overhead for what is already an error situation.

> ```
>     "frameStartedLoading",
>     "frameNavigated",
>     "domContentEventFired",
>     "loadEventFired",
>     "navigatedWithinDocument",
>     "frameStoppedLoading",
> ```

So we have analouges to most of these events, but we always provide the navigation id where appropriate whereas (afaict) with CDP you need the lifecycle events to get the navigation (loader) id. I'm not sure why they have different events for similar parts of the lifecycle with different properties, so if there's something I've missed in the design it would be good to know what it is :)

**Comment by foolip** [comment]
Fixed by https://github.com/w3c/webdriver-bidi/pull/93.
