### ISSUE TITLE
Issue 23: This doesn’t handle lone surrogates

### ISSUE THREAD

**Issue by lolaodelola** [w3c/webdriver-bidi#455]
Hi folks,

Have there been any discussions about how to handle [lone surrogates](https://w3c.github.io/webdriver-bidi/#issue-d33a79cf) in the `script.StringValue`? Do we want to throw an error to show invalidity or some other type?

**Comment by whimboo** [comment]
There was no discussion for BiDi yet but see https://github.com/w3c/webdriver/issues/1450 for the classic specification.

**Comment by mathiasbynens** [comment]
Other places where Web Platform APIs serialize/deserialize generic strings _do_ support lone surrogates:

- [`structuredClone()`](https://html.spec.whatwg.org/multipage/structured-data.html#structured-cloning)
- `JSON.stringify()` (serializes each lone surrogate as an escape sequence of the form `\uXXXX`) + `JSON.parse()`

I would prefer following this precedent, i.e. **option 1**.

Option 3 is another reasonable option but it comes with additional overhead that feels unnecessary.

IMHO option 2 (data loss) and option 4 (throwing) are inadequate.

**Comment by jrandolf** [comment]
I'm trying to understand where the confusion is here. Is the question here whether we want to only allow [USVString](https://mdn1.moz.one/en-US/docs/Web/API/USVString)s?

The specification is not necessarily explicit on what is allowed for strings, but implicitly in all Web standards, the definition for string is [DOMString](https://mdn1.moz.one/en-US/docs/Web/API/DOMString). In particular, `USVString` was defined to distinguish that case.

Considering we don't state anything about lone-surrogates, whether or not it is supported depends on the client and not WebDriver Bidi.

Perhaps that action item here is to explicitly define string in WebDriver Bidi as DOMString so there is no confusion.

**Comment by jgraham** [comment]
The confusion is basically "no one can decide whether JSON implementations are required to handle lone surrogates". The [RFC](https://datatracker.ietf.org/doc/html/rfc8259#section-8.2) rather unhelpfully says that the behaviour in this case is "unpredictable". The [ECMA Spec](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) arguably forbids lone surrogates (since strings are defined to be sequences of codepoints, and says that only codepoints may be escaped.

In practice we know that ES strings and DOMString values can and do contain lone surrogates, and that ECMA262 requires those to be serialized as escape sequences in JSON.

We also know that in practice many JSON implementations cannot consume these values, and that there are defacto interop problems caused by them (e.g. both geckodriver and safaridriver have difficulties with this).

In theory we could solve this by not using a JSON string to directly represent ECMAScript/DOM string values, but using some other form (at least for strings involving lone surrogates). In practice I doubt we're actually going to do that, but at the very least there should be a warning for client authors that they are likely to receive such values.

**Comment by jrandolf** [comment]
< The [ECMA Spec](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) arguably forbids lone surrogates (since strings are defined to be sequences of codepoints, and says that only codepoints may be escaped). But no doubt more than one reading is possible.

It strictly says

> A string is a sequence of Unicode code points wrapped with quotation marks (U+0022). All code points may be placed within the quotation marks except for the code points that must be escaped: quotation mark
(U+0022), reverse solidus (U+005C), and the control characters U+0000 to U+001F.

Everything else is normative. So I don't see how this _arguably forbids lone surrogates_.

> We also know that in practice many JSON implementations cannot consume these values, and that there are defacto interop problems caused by them (e.g. both geckodriver and safaridriver have difficulties with this).

Sounds like bugs related to geckodriver and safaridriver since JSON explicitly states that a string can be any sequence of Unicode code points except those that must be escaped: quotation mark (U+0022), reverse solidus (U+005C), and the control characters U+0000 to U+001F.

> At the very least there should be a warning for client authors that they are likely to receive such values.

I guess this means writing explicitly the normative behavior? I guess it wouldn't hurt!

**Comment by mathiasbynens** [comment]
> The [ECMA Spec](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) arguably forbids lone surrogates (since strings are defined to be sequences of codepoints, and says that only codepoints may be escaped). But no doubt more than one reading is possible.

Your claim is based on the premise that surrogate code points aren’t code points — but they are! It’s true that surrogate code points aren’t Unicode scalar values (perhaps this was the confusion?) but they are still code points.

Surrogate code points are code points. See https://unicode.org/faq/basic_q.html#13, https://www.unicode.org/glossary/#surrogate_code_point, and [Section 3.8 titled “Surrogates” in the Unicode Standard](https://www.unicode.org/versions/Unicode15.0.0/ch03.pdf#G2630).

**Comment by jrandolf** [comment]
> Maybe better than having a single warning would be to have a specific type for text data that may contain lone surrogates, and use it wherever the string ultimately comes from web content. Spec wise this would just be an alias for text, but it would allow implementations that have additional requirements around such data to know where they have to use a non-string type.

This is just `DOMString`. I think this all just goes back to the solution I proposed of inviting the `USVString` to our spec in cases where we need to make that distinction. On the other hand, there is no place we need that distinction, so it's sufficient to leave it as is since, again, in web specs, there is an implicit assumption that string means DOMString (which is the most relaxed definition).
