### ISSUE TITLE
Add browsingContext event to monitor history API usage

### ISSUE THREAD

**Issue by juliandescottes** [w3c/webdriver-bidi#502]
Current browsingContext events only cover regular page navigation or fragment navigation ([navigationStarted](https://w3c.github.io/webdriver-bidi/#event-browsingContext-navigationStarted), [fragmentNavigated](https://w3c.github.io/webdriver-bidi/#event-browsingContext-fragmentNavigated), ...)

For parity with https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-navigatedWithinDocument we could also expose additional events for history API usage.

**Comment by jgraham** [comment]
We previously had https://github.com/w3c/webdriver-bidi/issues/402 in which I suggested `fragmentNavigated` should cover this use case. But APIs like `pushState()` don't end up going through the navigation path in HTML and so aren't covered by that event as specified at present. So there are two options here:
* Change HTML so that we emit `fragmentNavigated` for anything that changes the position in the session history without changing the active document.
* Add a new event, specifically for the case where there isn't an actual navigation, but something is using one of the DOM APIs to create new history entries.

**Comment by OrKoN** [comment]
Option #1 sounds good to me.

**Comment by OrKoN** [comment]
Option #2 would require some implementation effort on our side but if there is a use case that is currently not covered, it sounds good too.

**Comment by OrKoN** [comment]
> speaking with my selenium hat on I think having a single event type is much easier DX for our users

sounds like a good argument for the option #1

**Comment by jrandolf** [comment]
I'd suggest renaming the `fragmentNavigated` event to something along the lines of `sameDocumentNavigated` and doing (1). If the use-case arises that we need to separate history and fragment navigation. We can add a type of the navigation.

**Comment by whimboo** [comment]
Removing or renaming an existing API disrupts our backward compatibility model with WebDriver. If we intend to introduce a new name such as `sameDocumentNavigated`, we may need to retain `frameNavigated` for the time being. We could consider marking it as deprecated and potentially remove it later once we are confident that clients have been updated?

**Comment by whimboo** [comment]
@OrKoN is there any more work to do or can we close the issue as well?

**Comment by OrKoN** [comment]
I think we can close it. There are more things that could be done such as adding the indication of the method that modifies the history or the serialized history state but I think it would make sense to wait for some client requests for those.

**Comment by whimboo** [comment]
Sounds fine. Thanks a lot for working on it!
