### ISSUE TITLE
Decide how to handle events that the client might miss

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#72]
There is a natural race between events that happen in the browser and the client subscribing to the relevant event stream. This means that a client may miss events that happened before the stream was enabled. There are a few use cases where this matters:

* Where the client wants to maintain a complete mapping of some browser-side resources e.g. a complete list of current browsing contexts.
* Where the client wants a complete list of transient events that occured e.g. a complete list of log events.

These are different in that in the first case the client is trying to replicate state that's current on the remote end, but in the latter case there isn't the same notion of the current state of the remote; it's just about buffering things that can be missed.

The solution that currently works in the spec for the state replication cases is to enable the desired events, and then read a the current state. The fact that this is two commands creates a race so something may get a creation event before the client has read the current state. This means the client will have to do deduplication. It also weakens invariants because it means that it's possible to e.g. get a `contextCreated` event for a context pointing to a parent that isn't yet known to the client.

For the pure-buffer cases where there isn't a current state to read, replicating this solution would involve having a command to get the buffer, which would only make sense in that one scenario; once you are subscribed to events presumably there's no point isn also maintaining a buffer.

So an obvious solution here is to provide a hook, so that when subscribing to certain events we immediately emit all the events to replicate the current state, or the buffered events. The problem in the current spec is we allow such fine-grained filtering of events it's not really clear how this should work. For example if browsing context A has a child B and you subscribe to `context` module events first for context B then for context A, you would clearly get a `contextCreated` event for B when subscibing to events for B, but it's unclear if you ought to get the same event again when you subscribe for A. It would be possible to write an algorithm so you get each event at most once, but it seems rather complex to explain the behaviour.

Assuming we think this is a problem that we want to solve, there are several options I can think of:

* Allow subscribing to top-level events in the new session command so you can be sure that the subscription happens before any events are sent. The subscription would be a capability alongside `websocketUrl`. This would only work for globally enabled events since at the time of new session we don't have browsing context ids. I think we should do this in any case, because in practice I think it will cover the most important use cases. But it doesn't cover all use cases.

* Only allow subscribing to events per top-level browsing context, not for any context. That makes things simpler (although there is still a decision to make if you first subscribe for a specific context and then later globally) and more or less matches what CDP has (but CDP doesn't smooth over out of process iframes; I assume we'd want to do that).

Spec-wise I think we're going to need a post-enable hook that an event can define to emit the initial events after it's enabled. For logging this will presumably involve an explicit buffer we put events in when they aren't to be emitted; for contexts &c. it will probably involve reading the current state and synthesising events we would have got.

**Comment by foolip** [comment]
This is challenging, thanks for filing the issue!

Ensuring that it's possible to subscribe before any events are emitted seems like a good option. But I wonder why it would need to be a capability? In a brand new session, before the client sends any commands, it could subscribe to the events it wants. It's only after the client sends its first command that the races begin, right?

For the case of a new `<iframe>` (browsing context id is not yet known), ensuring that no events are missed is indeed harder. Enabling them globally solves the problem, but short of that I can see these options:
- A way to subscribe to events for future browsing contexts of some description, like descendants of an existing browsing context. This might take the form of a "wait for browsing context and then enable these events" command. It's not a trivial model, though.
- A way to pause new browsing contexts before they can do anything, which CDP has. But I'm not sure how this works when the new browsing context is in the same process as another one.

@sadym-chromium this is an interesting issue, would be great to get your thoughts on it!

**Comment by jgraham** [comment]
If you start the session then the browser is going to start and the first browsing context is going to get created, so at the least there's a race there. Also depending on what exactly "first command" means a WebDriver HTTP connection could do arbitary things before a BiDi command is sent. GeckoDriver also support connecting to an existing browser instance, so I think that designing the protocol to allow reconstructing (some amount of) unobserved state would be better than trying to bake in the assumption that it's always in control.

**Comment by foolip** [comment]
> I think that designing the protocol to allow reconstructing (some amount of) unobserved state would be better than trying to bake in the assumption that it's always in control.

I think that's a good goal.

> If you start the session then the browser is going to start and the first browsing context is going to get created

I doubted this really needs to be the case, so I tried this with Puppeteer:
```js
const browser = await puppeteer.launch();
const pages = await browser.pages();
console.log(pages.length);
await browser.close();
```

It turns out that indeed there is an open page from the beginning. Maybe browsers could support launching headless without any initial page, I don't know.

I don't know if https://w3c.github.io/webdriver/ discussed this explicitly, but since it's possible to create a new session and then immediately navigate, there must be an initial "current top-level browsing context" in all implementations at least.

**Comment by jgraham** [comment]
I think on mac launching without any initial page is a reasonable possibility; on other platforms I expect the idea that there has to be at least a single window is quite thoroughly baked in (I could be wrong, of course).

In any case the initial window is only one case where the problem occurs. If we solve the general problem the first window case will naturally fall out.

**Comment by foolip** [comment]
I'm having a hard time imagining a solution to the general problem. Being able to connect to any browsing context and reconstruct everything that has happened would require buffering unlimited amounts of data just in case a client connects in the future. I think we have to accept some missed events are gone forever, but what we don't want is unavoidable race conditions even when you created the page (tree of browsing-contexts) where the events are happening.

Where the state is persistent on the browser side, like with the browsing context tree, cookies, permissions, cache, etc., we should provide ways of getting the current state and subscribing in a way that one can be sure to stay in sync, so ideally without a race condition between getting the current state and subscribing.

For things like logging, I could see a few options:
- ability to create a browsing context and subscribe to events as an atomic operation, where even the events of the initial `about:blank` would be caught (unclear if this is currently implementable over CDP)
- ability to subscribe for future child browsing contexts before they are created
- do nothing, require subscribing globally and then refining later to avoid too many events

**Comment by jgraham** [comment]
So to be clear I would consider anything that's not a regression compared with CDP to be an acceptable solution to the general problem. So from the point of view of a CDP-based implementation I'm not suggesting there ought to be unlimited buffering, but that we shouldn't end up throwing out events that were already buffered for us e.g in the case of console logs CDP has a buffer and will send the buffered events when you connect to a target for the first time (so when you open devtools you see existing logs). I'd like us to be able to do the same and get at least some log messages if you subscribe to the logs for a specific frame after the first message is sent.

The real question in my mind is whether the additional complexity from the per-context filtering system is worthwhile. Imagining there already exists a buffer for log events, one can imagine that every time you subscribe to log events in a new context, you go through the buffer and emit any events that are now allowed by the filter. That's arguably not too bad, but it's certianly easier if we only allowed filtering per top-level context.

For persistent state events we could do a tree diff thing to work out which events that wouldn't have been emitted by the previous state would now get emitted, although that could have problems where subscribing in a context and then unsubscribing and then resubscribing would re-emit events. It's unclear if that's desirable. Presumably it's what CDP does if you disable a domain for a target and then re-enable it, so maybe it's fine. If it's not I guess we need explicit buffers per browsing context for these events too, and some mechanism to remove events relating to stale state (e.g. script realms that were both created and destroyed). Agin this is easier if we just have global filters and top-level browsing context filters rather than per-bc filters.

**Comment by bwalderman** [comment]
Using only global and top-level browsing context filters rather than per-bc filters would at the very least match CDP's behavior and I think this would be an acceptable place to start.

Thinking about race conditions: since filtering on browsing contexts IDs requires knowing these IDs, there's always going to be some delay between a client discovering an ID for a context they are interested in, and making use of that ID. As long as we have solutions in place such as buffering logs, and diffing persistent state as described above, this might not be too bad. The client will eventually be caught up to the current state. This is mostly a concern for contexts that the client doesn't directly control though...

In situations where the client is the one creating a new browsing context, it's much easier to avoid race conditions. The client can create a fresh context navigated to about:blank, subscribe to any events they are interested in, and then proceed to navigate to the real page being tested. I like @foolip's suggestion which would streamline this process:

> ability to create a browsing context and subscribe to events as an atomic operation, where even the events of the initial about:blank would be caught (unclear if this is currently implementable over CDP)

I'm not sure how important the events of the initial about:blank would be in practice though. However, having a command that atomically creates a browsing contexts and subscribes to events might even make the about:blank step unnecessary. A user could create a new context, specify the events they want, and have it navigate directly to the actual URL they are interested in without worrying about missing anything.

**Comment by jgraham** [comment]
So from the telecon, I think the way forward here is:
* Restrict filters to top level browsing contexts
* For buffered events like console.log have an explicit buffer per top level context of events that aren't sent, with implementation-defined limits on the size
* For events that represent current state, arrange for the relevant events to be emitted when the filters change such that they are visible when they previously weren't visible.

**Comment by foolip** [comment]
> Restrict filters to top level browsing contexts

Would this amount to removing the `contexts` parameter, so it's only possible to filter by events? If so that's sounds good, a simpler model and we could revisit in the future and solve the problems raised in this issue then.

> For buffered events like console.log have an explicit buffer per top level context of events that aren't sent, with implementation-defined limits on the size

Are there any other known cases like this? I think for logs, the reason it works is that you can always open up devtools and see the logs, so that buffer is needed and exists already.

> For events that represent current state, arrange for the relevant events to be emitted when the filters change such that they are visible when they previously weren't visible.

Do you have an example of this? If the only remaining filtering is by event, does this just mean that we emit events immediately when you subscribe to get you up to date with the current state?

**Comment by jgraham** [comment]
> Would this amount to removing the contexts parameter, so it's only possible to filter by events? 

No it means that you can filter per top-level context, or globally, but not by nesting browsing contexts. It doesn't remove the possibility of subscribing to an event stream that was already enabled, but it does make things simpler.

> Are there any other known cases like this?

I don't know of any. I can imagine that network events *could* work like that (but e.g. performance events clearly wouldn't). In any case I'd say it should be case by case taking into account precedent and implementation concerns. There's certainly no desire to make some global event buffer.

> Do you have an example of this? If the only remaining filtering is by event, does this just mean that we emit events immediately when you subscribe to get you up to date with the current state?

Yes. e.g. if you subscribe to `browsingContext.created` events for context A, you'd immediately get the events for A and all ancestor browsing contexts of A, unless you had previously been subscribed to that event globally in which case you wouldn't get additional events.

**Comment by sadym-chromium** [comment]
Hi @jgraham!
You mentioned that
> Allow subscribing to top-level events in the new session command... But it doesn't cover all use cases.

I don't understand which cases this approach doesn't cover. Could you please clarify?

**Comment by jgraham** [comment]
> I don't understand which cases this approach doesn't cover. Could you please clarify?

It doesn't cover at least two use cases:
* Connecting to an existing session
* Not wanting to subscribe to events globally but wanting to subscribe for specific top level browsing contexts of interest.

**Comment by sadym-chromium** [comment]
Thanks!
* Do we want to support the passed events in the scenario "Connecting to an existing session"?
* What are the risks of subscribing to the events globally? I probably missing some of the context here, but why user cannot filter events themselves? Because of the protocol traffic overhead, or something else?

**Comment by jgraham** [comment]
* Do we want to support the passed events in the scenario "Connecting to an existing session"?

Yes, because we know that's a thing that's supported by existing protcols, and we shouldn't bake in design that forces us to be less functional than existing protocols.

* What are the risks of subscribing to the events globally? I probably missing some of the context here, but why user cannot filter events themselves? Because of the protocol traffic overhead, or something else?

Protocol traffic overhead is the biggest one. But it's also an optimistaion on the browser side; if the user is only subscribed to expensive events in a specific context then we only need to generate them for that context. That's a bigger concern for things like networking and performance events down the line.

**Comment by whimboo** [comment]
> I don't know of any. I can imagine that network events _could_ work like that (but e.g. performance events clearly wouldn't). In any case I'd say it should be case by case taking into account precedent and implementation concerns. There's certainly no desire to make some global event buffer.

Given the fact that specifically network events will happen a lot more than others, shall we define a maximum buffer size for events, or by event type? It would be good to see different implementations behave similar, and not that one just emits a couple of past events, and others a lot more. It's also a question of how much extra memory usage we are willed to see when holding all these events in a buffer. This could certainly become a bottleneck for low-powered machines and lesser available memory.

**Comment by k7z45** [comment]
I think the goal here is to enable client access to missing events for certain scenarios.
For example, after session creation but before connecting to BiDi WebSocket and subscribe to events or in the GeckoDriver case, supporting connection to existing browser instance. Any events before subscribing would be missing.
Part of the solution is to make the behavior of subscribing certain events to emit past events as well; this includes both the browsing context and logging events. Then every time we subscribe to them, we will get the whole history (under the buffer limit) as well as ongoing events.
Since this is only for certain events, I think it makes sense to have

> Allow subscribing to top-level events in the new session command so you can be sure that the subscription happens before any events are sent. The subscription would be a capability alongside websocketUrl. This would only work for globally enabled events since at the time of new session we don't have browsing context ids. I think we should do this in any case, because in practice I think it will cover the most important use cases. But it doesn't cover all use cases.

because it would enable client to catch any event without history. The disadvantage of this approach is that there is no way to specify browsing context so it's by default global (I think it's probably acceptable). It also does not cover connection to existing browser instance. 

These are my understanding so far.

> So from the telecon, I think the way forward here is:

> Restrict filters to top level browsing contexts
This would greatly reduce the complexity of dealing with duplicate events from subscribing to child browsing context.
> For buffered events like console.log have an explicit buffer per top level context of events that aren't sent, with implementation-defined limits on the size
So the implementation-defined limits could also be unlimited which I assume is how CDP console.log behaves.
>> For events that represent current state, arrange for the relevant events to be emitted when the filters change such that they are visible when they previously weren't visible.
> Yes. e.g. if you subscribe to browsingContext.created events for context A, you'd immediately get the events for A and all ancestor browsing contexts of A, unless you had previously been subscribed to that event globally in which case you wouldn't get additional events.

Since we are restricting filter to top level browsing context, we won't get ancestor browsing contexts for A. Instead, we would get history browsing context events for A and its descendant contexts.

Do you foresee any implementation concern for supporting events difference based on filter change given that clients could subscribe/unsubscribe and disconnect/re-connect?

**Comment by jgraham** [comment]
I think this was fixed by the changes to allow emitting events on subscribe.
