### ISSUE TITLE
Omit `id: null`

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#81]
According to the spec, 
> command id can be null, in which case the id field will also be set to null, not omitted from response.

Having `id: null` in each command seems redundant. I suggest to omit `id: null`.

**Comment by foolip** [comment]
I added that note to make the requirement clear in https://github.com/w3c/webdriver-bidi/pull/77, but I also think it would make sense to just note respond with an ID if none could be parsed.

The fix would be in https://w3c.github.io/webdriver-bidi/#respond-with-an-error, saying something like "with the id field set to *command id* if *command id* is not null and otherwise omitted".
