### ISSUE TITLE
Allow `maxDepth` serialisation setting

### ISSUE THREAD

**Issue by sadym-chromium** [w3c/webdriver-bidi#86]
The BiDi protocol can be used both on the local and remote hosts. As a BiDi user, I want to be able to configure the protocol behaviour by changing the serialisation depth.

Options:
1. Add a global number setting `serialisationMaxDepth`.
1. Add a global boolean flag `previewSerialisation` (switching between `serialisationMaxDepth=1` and `serialisationMaxDepth=0`)
1. Add an option to specify `maxDepth` in each request.

**Comment by jgraham** [comment]
So at the moment maxDepth is the only parameter, but as discussed in the previous telecon, there are other cases we don't consider, like very long arrays. We also have the problem events may contain serialized remote values so it's not possible to always request the depth we want on a case by case basis.

So I think one option here is to have some kind of heuristic that we use to estimate the serialized size, and have a way to cap that, which would account for both deep and broad objects. We'd also need a way to request additional data e.g. the ability to get an object without a different limit (or with a higher limit) or the ability to get an array-like with an offset from the start so that the data can be chunked.

One problem is that we don't have any mechanism to keep objects alive, so if we had e.g. `console.log(my_large_object)` and the output is truncated, but the object isn't referenced it may be gc'd before we have the chance to request more of the data. I'm not sure quite what we could do about that. We could have a way to request that objects are kept alive in the protocol, but we probably don't want to hold a reference to *very* object that's truncated since they are by definition going to be large.

**Comment by sadym-chromium** [comment]
For now we always can stick to default `maxDepth=1`, like in CDP.

**Comment by jgraham** [comment]
Can yo uexpand on what behaviour you're looking to support? I don't understand what use case you're trying to solve.

**Comment by sadym-chromium** [comment]
I try to understand how serialisation would work in some cases. I have following scenarios in mind:
1. `Runtime.evaluate` and other commands result:
  1.1. User receive a complex object, but they don't need all the data. Eg a huge array, which will be used as a function parameter.
  1.2. User receive a complex object, and they need all the values. Eg it's a result of serialisation function.
2. Events arguments.

Current approach in CDP command [`Runtime.evaluate`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate) is regulated by the flag `returnByValue` :
* `returnByValue: false` returns the result as a reference (with `objectID`) and with a preview.
* `returnByValue: true` returns the result as a JSON string, without references.

I still don't quite understand how to split those 2 approaches, and when to use which.

**Comment by sadym-chromium** [comment]
What if we delegate this kind of logic to users? We can return primitives and only references (`objectId`) to non-primitive instances like objects, arrays and functions. User can evaluate and serialise it themselves if they need to.

**Comment by jgraham** [comment]
That doesn't meet the goal of not requiring significant additional traffic compared to WebDriver. In particular WebDriver's Find Elements returns an array of N element references in a single request. We shouldn't require N+1 BiDi requests to get the same data back.

**Comment by whimboo** [comment]
@sadym-chromium can we close this issue based on the additions from https://github.com/w3c/webdriver-bidi/pull/385 which landed 3 days ago?

**Comment by sadym-chromium** [comment]
Sure. Thanks!
