### ISSUE TITLE
Update spec to define things in terms of Navigables

### ISSUE THREAD

**Issue by jgraham** [w3c/webdriver-bidi#91]
https://github.com/whatwg/html/pull/6315 is going to update the HTML spec to change the session history model, and introduce the concept of "navigables" which correspond to things in the browser that can be navigated. "Top-level navigables" are (usually) tabs and windows in the browser UI.

This concept of "top-level navigable" is exactly what WebDriver means by "window", and is in fact a better match for what we want to expose in the API than "top-level browsing context". That's because the top-level browsing context in a particular tab can change over time (e.g. with COOP/COEP). We don't necessarily need to expose those changes to the user, and in particular want to expose an identifier that's constant over the full life of the tab/window.

It's not clear to me if we should update everything related to browsing contexts to instead expose navigables (with or without changing all the naming), or if we should expose both seperately.

**Comment by foolip** [comment]
Since there's a "top-level navigable" I take it there's a tree of navigables. Does every navigable have a browsing context, and do browing contexts still form a tree by themselves, or only implicitly by each one belonging to a navigable. I'm hoping that we only need to expose one "frame tree".

**Comment by jgraham** [comment]
I think there's one tree at any given point in the session history. https://github.com/whatwg/html/pull/6315/files#diff-41cf6794ba4200b839c53531555f0f3998df4cbb01a4d5cb0b94e3ca5e23947dR82662-R82678 defines the properties of a navigable and if I've understood correctly, a navigable holds a list of browsing sessions, which hold a list of browsing contexts, but at any given time there's a 1:1 relationship between the active browsing contexts and navigables, however when you navigate through history the actual context changes.

Maybe @jakearchibald could confirm that's correct.

I think where we want to end up is that we use something that maps to navigable as the concept we expose to users as the handle to a specific tab/frame. In terms of selecting where commands should run, or where events originated the fact that they can only happen in active contexts means that we can unambiguously use navigables everywhere.

One question is what should happen if you run a script like `return window`. We want some way to get a handle that you can then pass into other commands e.g. so you can something like `let frame_id = session.execute_script("return frames[0]", navigable=top_level_id).await.navigable; session.navigate("http://example.org", navigable=frame_id);`. But it weould be weird if after the navigation returning the `WindowProxy` object from the new frame ended up with an indistinguishable response even though it refers to a different object. Maybe it should return something with both an object id that refers to the actual window object, and also an id of the navigable that you can use for other commands.

Another question is whether we want to actually use the term Navigable or if that's too obscure. I think my preference is to try to align with the spec terminology where possible, even if that isn't already familiar to client authors (I find the use of e.g. Page in CDP confusing, because it's hard to know what it actually represents).

**Comment by jakearchibald** [comment]
The idea is that a navigable has a current session history entry. The session history entry will have the browsing context & document.

The top-level navigable is "traversable", meaning it manages the session history of itself and nested navigables. It holds all the session history entries for itself and all nested navigables. It's responsible for assigning a session history entry to the current session history entry for a navigable.

I'm not set on this naming in case you have better ideas.

**Comment by jakearchibald** [comment]
> a navigable holds a list of browsing sessions

I had to change this relatively recently. It doesn't make sense for a navigable to hold its own session history, since the navigable can be destroyed (eg, an iframe when the parent page is unloaded) and later the session history can be reapplied to a different navigable (eg, an iframe when the parent page is reloaded by going 'back').

Now all the history data is in the "traversable" navigable, which is usually top-level (although that might not be true with prerender) https://github.com/whatwg/html/pull/6315/files#diff-41cf6794ba4200b839c53531555f0f3998df4cbb01a4d5cb0b94e3ca5e23947dR82753

**Comment by jgraham** [comment]
This HTML PR has merged!

So we need to audit BiDi to make sure we're correctly making the distinction between Browsing Context and Navigable. I think at the moment we are using context to mean both, although typically more in line with Navigable than Browsing Context, but there are probably also cases where we really mean the latter.

A question is whether, in cases where the `context` parameter is really about a specific navigable, are we in a position to change the protocol to match the newer terminology, or do we just have to document how we're using the term.

**Comment by whimboo** [comment]
As time passed by we now have clients implementing WebDriver BiDi and have picked up the module names, e.g. WebDriverIO automatically generates TypeScript code based on the CDDL definition.

As discussed with @jgraham it's most likely too late to make that change. Instead a section should be added to the BiDi spec explaining that the `browsingContext` term is outdated and basically refers to Navigable those days.

**Comment by domenic** [comment]
I would appreciate it if more work was done to update the spec to use navigables. Work like https://github.com/whatwg/html/pull/10329 is poking into bits of HTML that are not meant to be exposed. And I suspect the semantics of using browsing contexts is not correct, e.g. I doubt WebDriver BiDi clients intend to expose different IDs after a COOP-based browsing context swap within a single navigable.

Note: my request here is not related to naming or the public API, which seems to have been the topic of recent discussions in this thread. It is about having the spec manipulate and inspect navigables instead of browsing contexts, so that the HTML Standard can consider them an internal implementation detail of navigables as much as possible.
